// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArtistListDetail: typeof import('./src/components/list-detail/artistListDetail.vue')['default']
    Comment: typeof import('./src/components/list-detail/Comment/Comment.vue')['default']
    CommentItem: typeof import('./src/components/list-detail/Comment/CommentItem.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    ListDetail: typeof import('./src/components/list-detail/listDetail.vue')['default']
    ListDetailNav: typeof import('./src/components/list-detail/listDetailNav.vue')['default']
    ListDetailTop: typeof import('./src/components/list-detail/listDetailTop.vue')['default']
    LoginDialog: typeof import('./src/components/nav-aside/cpns/loginDialog.vue')['default']
    MusicList: typeof import('./src/components/music-list/musicList.vue')['default']
    MvList: typeof import('./src/components/mv-list/mvList.vue')['default']
    NavAside: typeof import('./src/components/nav-aside/NavAside.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/NavHeader.vue')['default']
    Player: typeof import('./src/components/player/player.vue')['default']
    PlayerDetail: typeof import('./src/components/player/playerDetail.vue')['default']
    PlayList: typeof import('./src/components/play-list/playList.vue')['default']
    PlayListHead: typeof import('./src/components/play-list-head/play-list-head.vue')['default']
    UserLogin: typeof import('./src/components/nav-aside/cpns/userLogin.vue')['default']
    VideoList: typeof import('./src/components/video-list/videoList.vue')['default']
  }
}

export { }
